version: '3'

services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard_home
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/tcp"
      - "68:68/udp"
      - "443:443/tcp"
      - "853:853/tcp"
    volumes:
      - ./adguard_data:/opt/adguardhome/work